### ISSUE TITLE
autoapprove a second time the same pull request

### ISSUE THREAD

**Issue by jsi-ka** [dkhmelenko/autoapproval#35]
Hi,

I am using autoapproval to approve pull requests generated by Renovate (https://github.com/renovatebot/renovate).

My problem is when a pull request was approved once and another changes is then added to the branch it requires another approval and autoapproval doesnt seem to be able to do that.

Does autoapproval can approval the same pull request several times or not ?

Thanks

**Comment by dkhmelenko** [comment]
This is similar to the previous issue https://github.com/dkhmelenko/autoapproval/issues/7

I would assume it will work if applied labels do not exist. Otherwise, the bot will think that PR was already approved.

**Comment by jsi-ka** [comment]
in my case we use "Dismiss stale pull request approvals when new commits are pushed" on all our repos so sometimes the PR get their autoapproval approvals dismissed.
I ended up creating my own glue code in ruby to scan and re-approve these PRs at the moment. Not proud of it

**Comment by dannyshaw** [comment]
@dkhmelenko We're butting up against this issue also. When dependabot rebases a PR it dismisses the approval and this app doesn't re-approve as the labels have been added. 

Is it possible to add a  configuration flag to ignore the label checking and just approve again?

Happy to submit a PR, though I'm not sure how I'd go testing it in action.

**Comment by jsi-ka** [comment]
I tried to set the applied label to none in the autoapproval config file but it didnt fix it as well
`apply_labels: []`
this won't work either ^

**Comment by dkhmelenko** [comment]
@jsi-ka Ok, got it. I will check what can be done in 1 week. Meanwhile, feel free to find suitable approaches and I can implement them soon.

@dannyshaw feel free to provide PR. I can get deeper into the issue also, but in a week, I'm not available atm.

The way how to test is using TDD and then you can run your solution locally (check [Probot documentation](https://probot.github.io/docs/http/) for that).

There is a potential solution: listen for the event `pull_request.review_request_removed`. But that could cause appropriate troubles.

As fas as I understood, your bots first do rebase (that's fine), autoapproval bot tries to approve it, but it is already approved. Then your bot deletes the stale review and autoapproval bot doesn't know about.

I let you think a bit about this solution, in case we all fine and agree having it, `autoapproval` bot can start listening for the event `pull_request.review_request_removed`. What do you think?

**Comment by dannyshaw** [comment]
I think we'd need to listen to `pull_request_review.dismissed` instead.  It would receive a slightly different payload, though inspecting the code it seems all the properties we currently care about would still be there.

We could check if the dismissed review was autoapprove's review by looking at `context.payload.review.user.login` and bypass the label checking in that circumstance?

https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent

Another approach instead of using the labels to determine if the PR requires an approval review, we could use the Github API to check if the PR has a non-dismissed review from autoapprove or not. This would make re-running the approval easier.

https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request

**Comment by dkhmelenko** [comment]
@dannyshaw @jsi-ka I prepared PR for handling the issue with the event `pull_request_review.dismissed` https://github.com/dkhmelenko/autoapproval/pull/45

Feel free to review it.

@dannyshaw Regarding checking approval review through the Github API - I think it is a good idea, but I will do that in separate PR in order to have atomic changes.

**Comment by dkhmelenko** [comment]
@dannyshaw  I created a separate issue for that https://github.com/dkhmelenko/autoapproval/issues/46

**Comment by jsi-ka** [comment]
great stuff ! Is this feature deployed in github ?
I dont see the difference yet... Maybe I am too impatient ? 
- first autoapproval to my repo
- new commit that dismissed the approval "jsi-ka dismissed autoapproval’s stale review via 57183e1 17 minutes ago"
- no re-approval at the moment..

**Comment by dkhmelenko** [comment]
Actually I have to acknowledge it has a bug:

when we check an event `pull_request_review.dismissed` it contains information about the user who dismissed the review, not who submitted a review. 

Give me a few days and I will provide a solution to check the user who submitted info.

@dannyshaw I think I will apply your suggestion by using Github API for that.

**Comment by dkhmelenko** [comment]
@dannyshaw This PR https://github.com/dkhmelenko/autoapproval/pull/53 should fix the issue

**Comment by dkhmelenko** [comment]
@jsi-ka Please let me know if it works for you

**Comment by jsi-ka** [comment]
hello, I am afraid it s still not re-approving it
My config is 
`from_owner:
  - jsi-ka
required_labels:
  - renovate
apply_labels: []`
and when I push a change in the branch the approval is dismissed but doesnt come back

**Comment by dkhmelenko** [comment]
Ok, now it's fixed here https://github.com/dkhmelenko/autoapproval/pull/76. I checked and it works for me. Feel free to reopen the issue if something doesn't work.
